name: Tracker
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared

      - name: Run tracker
        run: |
          python server.py &
          sleep 3
          ./cloudflared tunnel --url http://localhost:8080 2>&1 | grep --line-buffered -o 'https://[a-z0-9-]*\.trycloudflare\.com'
