name: Tracker
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared

      - name: Run tracker
        env:
          CF_TUNNEL_TOKEN: ${{ secrets.CF_TUNNEL_TOKEN }}
        run: |
          python server.py &
          sleep 3
          ./cloudflared tunnel run --token $CF_TUNNEL_TOKEN
